### ISSUE TITLE
Mixcloud Download Unresponsive

### ISSUE THREAD

**Issue by LyallPivo** [mixcloud-downloader/chrome-extension#2]
When I try to open the Downloader on any Mixcloud page, the same "Connection Reset' error message appears instead of the application downloading the mix. ERR_CONNECTION_RESET. The Internet connection is not a problem.

**Comment by mixcloud-downloader** [comment]
Do you still have this issue? It might well have been resolved in the mean time, as I had during that time a partial server outage. If you still have that issue I need to know this things:

- The country from which you are using the downloader
- One example page which doesn't work
